services:
  postgres:
    image: postgres:16
    container_name: turkpdr_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: turkpdr
    ports:
      - "5432:5432"
    volumes:
      - turkpdr_pgdata:/var/lib/postgresql/data

volumes:
  turkpdr_pgdata: